BakeryWebApp/Models/ProductsMaterial.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace BakeryWebApp
{
    public partial class ProductsMaterial
    {
        [Key]
        public int ProductMaterial { get; set; }
        public int? MaterialId { get; set; }
        public int? ProductId { get; set; }
        [Display(Name = "Количество")]
        [Range(1, int.MaxValue)]
        public double? Quantity { get; set; }

        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}

BakeryWebApp/Controllers/ProductsMaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryWebApp;
using Microsoft.Extensions.Caching.Memory;
using BakeryWebApp.ViewModels;

namespace BakeryWebApp.Controllers
{
    public class ProductsMaterialsController : Controller
    {
        private readonly BakeryContext _context;
        private IMemoryCache _memoryCache;

        public ProductsMaterialsController(BakeryContext context, IMemoryCache cache)
        {
            _context = context;
            _memoryCache = cache;
        }
        public IActionResult Index(string materialName, string productName, double quantity, SortState sortState, int page = 1)
        {
            IEnumerable<ProductsMaterial> productsMaterials = _context.ProductsMaterials.Include(m => m.Material).Include(p => p.Product);
            if (materialName == null)
                _memoryCache.TryGetValue("materialNameProductMaterial", out materialName);
            else
            {
                _memoryCache.Set("materialNameProductMaterial", materialName);
                productsMaterials = productsMaterials.Where(n => n.Material.MaterialName.Contains(materialName));
            }
            if (productName == null)
                _memoryCache.TryGetValue("productNameProductMaterial", out productName);
            else
            {
                _memoryCache.Set("productNameProductMaterial", productName);
                productsMaterials = productsMaterials.Where(n => n.Product.ProductName.Contains(productName));
            }
            if (quantity == 0)
                _memoryCache.TryGetValue("quanityProductMaterial", out quantity);
            else
            {
                _memoryCache.Set("quantityProductMaterial", quantity);
                productsMaterials = productsMaterials.Where(n => n.Quantity == quantity);
            }
            if (sortState == SortState.No)
                _memoryCache.TryGetValue("productMaterialSort", out sortState);
            else
            {
                _memoryCache.Set("productMaterialSort", sortState);
                productsMaterials = Sort(productsMaterials, sortState);
            }
            int count = productsMaterials.Count();
            int pageSize = 15;
            productsMaterials = productsMaterials.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ProductMaterialViewModel viewModel = new ProductMaterialViewModel
            {
                ProductsMaterials = productsMaterials,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortState),
                MaterialName = materialName,
                ProductionName = productName,
                Quantity = quantity

            };
            return View(viewModel);
        }

        public IActionResult Create()
        {
            ViewData["MaterialId"] = new SelectList(_context.Materials, "MaterialId", "MaterialName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductMaterial,MaterialId,ProductId,Quantity")] ProductsMaterial productsMaterial)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productsMaterial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialId"] = new SelectList(_context.Materials, "MaterialId", "MaterialName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsMaterial);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsMaterial = await _context.ProductsMaterials.FindAsync(id);
            if (productsMaterial == null)
            {
                return NotFound();
            }
            ViewData["MaterialId"] = new SelectList(_context.Materials, "MaterialId", "MaterialName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsMaterial);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductMaterial,MaterialId,ProductId,Quantity")] ProductsMaterial productsMaterial)
        {
            if (id != productsMaterial.ProductMaterial)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productsMaterial);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsMaterialExists(productsMaterial.ProductMaterial))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialId"] = new SelectList(_context.Materials, "MaterialId", "MaterialName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsMaterial);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsMaterial = await _context.ProductsMaterials
                .Include(p => p.Material)
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.ProductMaterial == id);
            if (productsMaterial == null)
            {
                return NotFound();
            }

            return View(productsMaterial);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productsMaterial = await _context.ProductsMaterials.FindAsync(id);
            _context.ProductsMaterials.Remove(productsMaterial);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsMaterialExists(int id)
        {
            return _context.ProductsMaterials.Any(e => e.ProductMaterial == id);
        }
        private IEnumerable<ProductsMaterial> Sort(IEnumerable<ProductsMaterial> productsMaterials, SortState sortState)
        {
            switch (sortState)
            {
                case SortState.ProductMaterialMaterialAcs:
                    productsMaterials = productsMaterials.OrderBy(m => m.Material.MaterialName);
                    break;
                case SortState.ProductMaterialMaterialDecs:
                    productsMaterials = productsMaterials.OrderByDescending(m => m.Material.MaterialName);
                    break;
                case SortState.ProductMaterialProductAcs:
                    productsMaterials = productsMaterials.OrderBy(p => p.Product.ProductName);
                    break;
                case SortState.ProductMaterialProductDecs:
                    productsMaterials = productsMaterials.OrderBy(p => p.Product.ProductName);
                    break; ;
                case SortState.ProductMaterialQuantityAcs:
                    productsMaterials = productsMaterials.OrderBy(q => q.Quantity);
                    break;
                case SortState.ProductMaterialQuantityDecs:
                    productsMaterials = productsMaterials.OrderBy(q => q.Quantity);
                    break;
            }
            return productsMaterials;
        }

        public IActionResult ClearFilter()
        {
            _memoryCache.Remove("materialNameProductMaterial");
            _memoryCache.Remove("productNameProductMaterial");
            _memoryCache.Remove("quanityProductMaterial");
            _memoryCache.Remove("productMaterialSort");
            return RedirectToAction("Index");
        }
    }
}

BakeryWebApp/Views/ProductsMaterials/Create.cshtml
@model BakeryWebApp.ProductsMaterial

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить</h1>

<h4>Материал в изделиях</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaterialId" class="control-label">Наименование материала</label>
                <select asp-for="MaterialId" class ="form-control" asp-items="ViewBag.MaterialId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Наименование изделия</label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/ProductsMaterials/Delete.cshtml
@model BakeryWebApp.ProductsMaterial

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<div>
    <h4>Материал в изделиях</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material.MaterialName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material.MaterialName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductMaterial" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
    </form>
</div>

BakeryWebApp/Views/ProductsMaterials/Edit.cshtml
@model BakeryWebApp.ProductsMaterial

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменеие</h1>

<h4>Материал в изделиях</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductMaterial" />
            <div class="form-group">
                <label asp-for="MaterialId" class="control-label">Наименование материала</label>
                <select asp-for="MaterialId" class="form-control" asp-items="ViewBag.MaterialId"></select>
                <span asp-validation-for="MaterialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Наименование изделия</label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/ProductsMaterials/Index.cshtml
@model BakeryWebApp.ViewModels.ProductMaterialViewModel

@{
    ViewData["Title"] = "Index";
}
<div class="bg-light">
    <div class="text-center"><h1>Нормы материлов</h1></div>
    <div class="row, text-left">
        <p>
            <a class="btn btn-outline-dark" asp-action="Create">Добавить</a>
            <a class="btn btn-outline-dark" asp-action="ClearFilter">Очистить фильтр</a>
        </p>
    </div>
    <div class="row, text-left">
        @using (Html.BeginForm("Index", "ProductsMaterials", FormMethod.Get))
        {
            <fieldset>
                Изделие: @Html.TextBox("productName", Model.ProductionName)
                Материал: @Html.TextBox("materialName", Model.MaterialName)
                Количество материала: @Html.TextBox("quantity", Model.Quantity)
                <input class="btn btn-outline-dark" type="submit" value="Найти" />
            </fieldset>
        }
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductMaterialProductSort>
                    @Html.DisplayNameFor(model => model.ProductsMaterials.FirstOrDefault().Product.ProductName)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductMaterialMaterialSort>
                    @Html.DisplayNameFor(model => model.ProductsMaterials.FirstOrDefault().Material.MaterialName)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductMaterialQuantitySort>
                    @Html.DisplayNameFor(model => model.ProductsMaterials.FirstOrDefault().Quantity)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ProductsMaterials)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Material.MaterialName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.ProductMaterial">Изменить</a> |
                <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.ProductMaterial">Удалить</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}