BakeryWebApp/Models/Material.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace BakeryWebApp
{
    public partial class Material
    {
        [Key]
        public int MaterialId { get; set; }
        [Display(Name = "Наименование материала")]
        [StringLength(50, MinimumLength =3)]
        public string MaterialName { get; set; }

        public virtual ICollection<ProductsMaterial> ProductsMaterials { get; set; }
    }
}

BakeryWebApp/ViewModels/MaterialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BakeryWebApp.ViewModels
{
    public class MaterialViewModel
    {
        public IEnumerable<Material> Materials { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public string MaterialName { get; set; }
    }
}

BakeryWebApp/Controllers/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryWebApp;
using BakeryWebApp.ViewModels;

namespace BakeryWebApp.Controllers
{
    public class MaterialsController : Controller
    {
        private readonly BakeryContext _context;

        public MaterialsController(BakeryContext context)
        {
            _context = context;
        }

        public IActionResult Index(string materialName, int page = 1)
        {
            if (materialName == null)
                HttpContext.Request.Cookies.TryGetValue("materialName", out materialName);
            else
                HttpContext.Response.Cookies.Append("materialName", materialName);
            IEnumerable<Material> materials = _context.Materials;
            int pageSize = 15;
            if (materialName != null)
                materials = materials.Where(n => n.MaterialName.Contains(materialName));
            int count = materials.Count();
            materials = materials.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            MaterialViewModel viewModel = new MaterialViewModel
            {
                Materials = materials,
                PageViewModel = new PageViewModel(count, page, pageSize),
                MaterialName = materialName

            };
            return View(viewModel);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaterialId,MaterialName")] Material material)
        {
            if (ModelState.IsValid)
            {
                _context.Add(material);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materials.FindAsync(id);
            if (material == null)
            {
                return NotFound();
            }
            return View(material);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaterialId,MaterialName")] Material material)
        {
            if (id != material.MaterialId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(material);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaterialExists(material.MaterialId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materials
                .FirstOrDefaultAsync(m => m.MaterialId == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var material = await _context.Materials.FindAsync(id);
            var materialProduct = _context.ProductsMaterials.Where(m => m.MaterialId == id);
            _context.ProductsMaterials.RemoveRange(materialProduct);
            _context.Materials.Remove(material);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialExists(int id)
        {
            return _context.Materials.Any(e => e.MaterialId == id);
        }

        public IActionResult ClearCache()
        {
            HttpContext.Response.Cookies.Delete("materialName");
            return RedirectToAction("Index");
        }
    }
}

BakeryWebApp/Views/Materials/Create.cshtml
@model BakeryWebApp.Material

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить</h1>

<h4>Материал</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaterialName" class="control-label"></label>
                <input asp-for="MaterialName" class="form-control" />
                <span asp-validation-for="MaterialName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/Materials/Delete.cshtml
@model BakeryWebApp.Material

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<div>
    <h4>Материал</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaterialName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaterialName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaterialId" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
    </form>
</div>

BakeryWebApp/Views/Materials/Edit.cshtml
@model BakeryWebApp.Material

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменение</h1>

<h4>Материал</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaterialId" />
            <div class="form-group">
                <label asp-for="MaterialName" class="control-label"></label>
                <input asp-for="MaterialName" class="form-control" />
                <span asp-validation-for="MaterialName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/Materials/Index.cshtml
@model BakeryWebApp.ViewModels.MaterialViewModel

@{
    ViewData["Title"] = "Index";
}
<div class="bg-light">
    <div class="text-center"><h1>Материалы</h1></div>
    <div class="row, text-left">
        <p>
            <a class="btn btn-outline-dark" asp-action="Create">Добавить</a>
            <a class="btn btn-outline-dark" asp-action="ClearCache">Очистить фильтр</a>
            </p>
    </div>
    <div class="row, text-left">
        @using (Html.BeginForm("Index", "Materials", FormMethod.Get))
        {
            <fieldset>
                Наименование материала: @Html.TextBox("materialName", Model.MaterialName)
                <input class="btn btn-outline-dark" type="submit" value="Найти" />
            </fieldset>
        }
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Materials.FirstOrDefault().MaterialName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Materials)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaterialName)
                </td>
                <td>
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.MaterialId">Изменить</a> |
                    <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.MaterialId">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}