BakeryWebApp/Controllers/NormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryWebApp;
using Microsoft.Extensions.Caching.Memory;
using BakeryWebApp.ViewModels;

namespace BakeryWebApp.Controllers
{
    public class NormsController : Controller
    {
        private readonly BakeryContext _context;
        private IMemoryCache _memoryCache;

        public NormsController(BakeryContext context, IMemoryCache cache)
        {
            _context = context;
            _memoryCache = cache;
        }

        public IActionResult Index(string rawName, string productName, double quantity, SortState sortState, int page = 1)
        {
            IEnumerable<Norm> norms = _context.Norms.Include(r => r.Raw).Include(p => p.Product);
            if (rawName == null)
                _memoryCache.TryGetValue("rawNameNorm", out rawName);
            else
            {
                _memoryCache.Set("rawNameNorm", rawName);
                norms = norms.Where(n => n.Raw.RawName.Contains(rawName));
            }
            if (productName == null)
                _memoryCache.TryGetValue("productNameNorm", out productName);
            else
            {
                _memoryCache.Set("productNameNorm", productName);
                norms = norms.Where(n => n.Product.ProductName.Contains(productName));
            }
            if (quantity == 0)
                _memoryCache.TryGetValue("quanityNorm", out quantity);
            else
            {
                _memoryCache.Set("quantityNorm", quantity);
                norms = norms.Where(n => n.Quantity == quantity);
            }
            if (sortState == SortState.No)
                _memoryCache.TryGetValue("normSort", out sortState);
            else
            {
                _memoryCache.Set("normSort", sortState);
                norms = Sort(norms, sortState);
            }
            int count = norms.Count();
            int pageSize = 15;
            norms = norms.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            NormViewModel viewModel = new NormViewModel
            {
                Norms = norms,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortState),
                RawName = rawName,
                ProductionName = productName,
                Quantity = quantity

            };
            return View(viewModel);
        }

        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["RowId"] = new SelectList(_context.Raws, "RawId", "RawName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NormId,RowId,ProductId,Quantity")] Norm norm)
        {

            if (norm.Quantity > 0)
            {
                _context.Add(norm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["RowId"] = new SelectList(_context.Raws, "RawId", "RawName");
            return View(norm);
        }

        // GET: Norms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var norm = await _context.Norms.FindAsync(id);
            if (norm == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["RowId"] = new SelectList(_context.Raws, "RawId", "RawName");
            return View(norm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NormId,RowId,ProductId,Quantity")] Norm norm)
        {
            if (id != norm.NormId)
            {
                return NotFound();
            }

            if (norm.Quantity > 0)
            {
                try
                {
                    _context.Update(norm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NormExists(norm.NormId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["RowId"] = new SelectList(_context.Raws, "RawId", "RawName");
            return View(norm);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var norm = await _context.Norms
                .Include(n => n.Product)
                .Include(n => n.Raw)
                .FirstOrDefaultAsync(m => m.NormId == id);
            if (norm == null)
            {
                return NotFound();
            }

            return View(norm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var norm = await _context.Norms.FindAsync(id);
            _context.Norms.Remove(norm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NormExists(int id)
        {
            return _context.Norms.Any(e => e.NormId == id);
        }

        private IEnumerable<Norm> Sort(IEnumerable<Norm> norms, SortState sortState)
        {
            switch (sortState)
            {
                case SortState.NormRawNameAcs:
                    norms = norms.OrderBy(r => r.Raw.RawName);
                    break;
                case SortState.NormRawNameDecs:
                    norms = norms.OrderByDescending(r => r.Raw.RawName);
                    break;
                case SortState.NormProductNameAcs:
                    norms = norms.OrderBy(p => p.Product.ProductName);
                    break;
                case SortState.NormProductNameDecs:
                    norms = norms.OrderByDescending(p => p.Product.ProductName);
                    break;
                case SortState.NormQuantityAcs:
                    norms = norms.OrderBy(q => q.Quantity);
                    break;
                case SortState.NormQuantityDecs:
                    norms = norms.OrderByDescending(q => q.Quantity);
                    break;
            }
            return norms;
        }

        public IActionResult ClearFilter()
        {
            _memoryCache.Remove("rawNameNorm");
            _memoryCache.Remove("productNameNorm");
            _memoryCache.Remove("quanityNorm");
            _memoryCache.Remove("normSort");
            return RedirectToAction("Index");
        }
    }
}

BakeryWebApp/Controllers/RawsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryWebApp;
using BakeryWebApp.ViewModels;

namespace BakeryWebApp.Controllers
{
    public class RawsController : Controller
    {
        private readonly BakeryContext _context;

        public RawsController(BakeryContext context)
        {
            _context = context;
        }


        public IActionResult Index(string rawName, int page = 1)
        {
            if(rawName == null)
                HttpContext.Request.Cookies.TryGetValue("rawName", out rawName);
            else
                HttpContext.Response.Cookies.Append("rawName", rawName);
            IEnumerable<Raw> raws = _context.Raws;
            int pageSize = 15;
            if(rawName != null)
                raws = raws.Where(n => n.RawName.Contains(rawName));
            int count = raws.Count();
            raws = raws.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            RawViewModel viewModel = new RawViewModel
            {
                Raws = raws,
                PageViewModel = new PageViewModel(count, page, pageSize),
                RawName = rawName
            };
            return View(viewModel);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RawId,RawName")] Raw raw)
        {
            if (ModelState.IsValid)
            {
                _context.Add(raw);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(raw);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var raw = await _context.Raws.FindAsync(id);
            if (raw == null)
            {
                return NotFound();
            }
            return View(raw);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RawId,RawName")] Raw raw)
        {
            if (id != raw.RawId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raw);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RawExists(raw.RawId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(raw);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var raw = await _context.Raws
                .FirstOrDefaultAsync(m => m.RawId == id);
            if (raw == null)
            {
                return NotFound();
            }

            return View(raw);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var raw = await _context.Raws.FindAsync(id);
            var norms = _context.Norms.Where(n => n.RowId == id);
            _context.Norms.RemoveRange(norms);
            _context.Raws.Remove(raw);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RawExists(int id)
        {
            return _context.Raws.Any(e => e.RawId == id);
        }

        public IActionResult ClearCache()
        {
            HttpContext.Response.Cookies.Delete("rawName");
            return RedirectToAction("Index");
        }
    }
}

BakeryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BakeryWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Хлебзавод</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Raws" asp-action="Index">Сырье</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materials" asp-action="Index">Материалы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Изделия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Norms" asp-action="Index">Нормы сырья</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsMaterials" asp-action="Index">Нормы материала</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsPlans" asp-action="Index">План производства изделий</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsProductions" asp-action="Index">Выпущенные изделия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Отчёты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Хлебзавод
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>