BakeryWebApp/Models/ProductsPlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace BakeryWebApp
{
    public partial class ProductsPlan
    {
        [Key]
        public int ProductPlan { get; set; }
        public int? DayPlanId { get; set; }
        public int? ProductId { get; set; }
        [Display(Name = "Количество изделий")]
        [Range(1, int.MaxValue)]
        public int? Count { get; set; }

        public virtual DayPlan DayPlan { get; set; }
        public virtual Product Product { get; set; }
    }
}

BakeryWebApp/ViewModels/ProductsPlansViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BakeryWebApp.ViewModels
{
    public class ProductsPlansViewModel
    {
        public IEnumerable<ProductsPlan> ProductsPlans { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public SortViewModel SortViewModel { get; set; }
        public string ProductName { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime PlanDate { get; set; }
        public int Count { get; set; }
        public ProductsPlan ProductsPlan { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Число")]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }
    }
}

BakeryWebApp/Controllers/ProductsPlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryWebApp;
using Microsoft.Extensions.Caching.Memory;
using BakeryWebApp.ViewModels;

namespace BakeryWebApp.Controllers
{
    public class ProductsPlansController : Controller
    {
        private readonly BakeryContext _context;
        private IMemoryCache _memoryCache;

        public ProductsPlansController(BakeryContext context, IMemoryCache cache)
        {
            _context = context;
            _memoryCache = cache;
        }

        public IActionResult Index(DateTime planDate, SortState sortState, int countOfProd, string productName, int page = 1)
        {
            IEnumerable<ProductsPlan> productsPlans = _context.ProductsPlans.Include(p => p.DayPlan).Include(p => p.Product);
            if (planDate == default)
                _memoryCache.TryGetValue("productPlanDate", out planDate);
            else
            {
                _memoryCache.Set("productPlanDate", planDate);
                productsPlans = productsPlans.Where(p => p.DayPlan.Date.Equals(planDate));
            }
            if (productName == null)
                _memoryCache.TryGetValue("productNamePlan", out productName);
            else
            {
                _memoryCache.Set("productNamePlan", productName);
                productsPlans = productsPlans.Where(n => n.Product.ProductName.Contains(productName));
            }
            if (countOfProd == 0)
                _memoryCache.TryGetValue("countProductPlan", out countOfProd);
            else
            {
                _memoryCache.Set("countProductPlan", countOfProd);
                productsPlans = productsPlans.Where(p => p.Count == countOfProd);
            }
            if (sortState == SortState.No)
                _memoryCache.TryGetValue("productPlanSort", out sortState);
            else
            {
                _memoryCache.Set("productPlanSort", sortState);
                productsPlans = Sort(productsPlans, sortState);
            }
            int count = productsPlans.Count();
            int pageSize = 15;
            productsPlans = productsPlans.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ProductsPlansViewModel viewModel = new ProductsPlansViewModel
            {
                ProductsPlans = productsPlans,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortState),
                PlanDate = planDate,
                ProductName = productName,
                Count = countOfProd

            };
            return View(viewModel);
        }

        public IActionResult Create()
        {
            ViewData["DayPlanId"] = new SelectList(_context.DayPlans, "DayPlanId", "Date");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductsPlansViewModel productsPlansViewModel)
        {
            DayPlan dayPlans = _context.DayPlans.Where(d => d.Date.Equals(productsPlansViewModel.Date)).FirstOrDefault();
            if (dayPlans == null)
            {
                _context.DayPlans.Add(new DayPlan { Date = productsPlansViewModel.Date });
                await _context.SaveChangesAsync();
                dayPlans = _context.DayPlans.Where(d => d.Date.Equals(productsPlansViewModel.Date)).FirstOrDefault();
            }
            ProductsPlan productsPlan = productsPlansViewModel.ProductsPlan;
            productsPlan.DayPlanId = dayPlans.DayPlanId;
            if (ModelState.IsValid)
            {
                _context.Add(productsPlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DayPlanId"] = new SelectList(_context.DayPlans, "DayPlanId", "Date");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsPlan);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsPlan = await _context.ProductsPlans.FindAsync(id);
            ProductsPlansViewModel productsPlansViewModel = new ProductsPlansViewModel
            {
                ProductsPlan = productsPlan
            };
            if (productsPlan == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsPlansViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductsPlansViewModel productsPlansViewModel)
        {
            if (id != productsPlansViewModel.ProductsPlan.ProductPlan)
            {
                return NotFound();
            }
            DayPlan dayPlans = _context.DayPlans.Where(d => d.Date.Equals(productsPlansViewModel.Date)).FirstOrDefault();
            if (dayPlans == null)
            {
                _context.DayPlans.Add(new DayPlan { Date = productsPlansViewModel.Date });
                await _context.SaveChangesAsync();
                dayPlans = _context.DayPlans.Where(d => d.Date.Equals(productsPlansViewModel.Date)).FirstOrDefault();
            }
            ProductsPlan productsPlan = productsPlansViewModel.ProductsPlan;
            productsPlan.DayPlanId = dayPlans.DayPlanId;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productsPlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsPlanExists(productsPlan.ProductPlan))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DayPlanId"] = new SelectList(_context.DayPlans, "DayPlanId", "Date");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            return View(productsPlan);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsPlan = await _context.ProductsPlans
                .Include(p => p.DayPlan)
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.ProductPlan == id);
            if (productsPlan == null)
            {
                return NotFound();
            }

            return View(productsPlan);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productsPlan = await _context.ProductsPlans.FindAsync(id);
            _context.ProductsPlans.Remove(productsPlan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsPlanExists(int id)
        {
            return _context.ProductsPlans.Any(e => e.ProductPlan == id);
        }
        private IEnumerable<ProductsPlan> Sort(IEnumerable<ProductsPlan> productsPlans, SortState sortState)
        {
            switch (sortState)
            {
                case SortState.ProductPlanDateAcs:
                    productsPlans = productsPlans.OrderBy(d => d.DayPlan.Date);
                    break;
                case SortState.ProductPlanDateDecs:
                    productsPlans = productsPlans.OrderByDescending(d => d.DayPlan.Date);
                    break;
                case SortState.ProductPlanProductAcs:
                    productsPlans = productsPlans.OrderBy(p => p.Product.ProductName);
                    break;
                case SortState.ProductPlanProductDecs:
                    productsPlans = productsPlans.OrderByDescending(p => p.Product.ProductName);
                    break;
                case SortState.ProductPlanCountAcs:
                    productsPlans = productsPlans.OrderBy(c => c.Count);
                    break;
                case SortState.ProductPlanCountDecs:
                    productsPlans = productsPlans.OrderByDescending(c => c.Count);
                    break;
            }
            return productsPlans;
        }

        public IActionResult ClearFilter()
        {
            _memoryCache.Remove("productPlanDate");
            _memoryCache.Remove("productNamePlan");
            _memoryCache.Remove("countProductPlan");
            _memoryCache.Remove("productPlanSort");
            return RedirectToAction("Index");
        }
    }
}

BakeryWebApp/Views/ProductsPlans/Create.cshtml
@model BakeryWebApp.ViewModels.ProductsPlansViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Добавление</h1>

<h4>План проивоздства</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductsPlan.ProductId" class="control-label">Наименование изделия</label>
                <select asp-for="ProductsPlan.ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductsPlan.Count" class="control-label"></label>
                <input asp-for="ProductsPlan.Count" class="form-control" />
                <span asp-validation-for="ProductsPlan.Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/ProductsPlans/Delete.cshtml
@model BakeryWebApp.ProductsPlan

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<div>
    <h4>План проивоздства</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DayPlan.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DayPlan.Date)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductPlan" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
    </form>
</div>

BakeryWebApp/Views/ProductsPlans/Edit.cshtml
@model BakeryWebApp.ViewModels.ProductsPlansViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменение</h1>

<h4>План проивоздства</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductsPlan.ProductPlan" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductsPlan.ProductId" class="control-label">Наименование изделия</label>
                <select asp-for="ProductsPlan.ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductsPlan.Count" class="control-label"></label>
                <input asp-for="ProductsPlan.Count" class="form-control" />
                <span asp-validation-for="ProductsPlan.Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BakeryWebApp/Views/ProductsPlans/Index.cshtml
@model BakeryWebApp.ViewModels.ProductsPlansViewModel

@{
    ViewData["Title"] = "Index";
}
<div class="bg-light">
    <div class="text-center"><h1>План проивоздства</h1></div>
    <div class="row, text-left">
        <p>
            <a class="btn btn-outline-dark" asp-action="Create">Добавить</a>
            <a class="btn btn-outline-dark" asp-action="ClearFilter">Очистить фильтр</a>
        </p>
    </div>
    @using (Html.BeginForm("Index", "ProductsPlans", FormMethod.Get))
    {
        <div class="row">
            <div class="col-md-3">
                <label>Изделие</label>
                @Html.TextBox("productName", Model.ProductName)
            </div>
            <div class="col-md-3">
                <label>Дата</label>
                <input asp-for="PlanDate"/>
            </div>
            <div class="col-md-4">
                <label>Количество</label>
                @Html.TextBox("countOfProd", Model.Count)
            </div>
            <div class="col-md-2">
                <input class="btn btn-outline-dark" type="submit" value="Найти" />
            </div>
        </div>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductPlanProductSort>
                    @Html.DisplayNameFor(model => model.ProductsPlans.FirstOrDefault().Product.ProductName)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductPlanDateSort>
                    @Html.DisplayNameFor(model => model.ProductsPlans.FirstOrDefault().DayPlan.Date)
                </a>
            </th>

            <th>
                <a asp-action="Index" asp-route-sortState=@Model.SortViewModel.ProductPlanCountSort>
                    @Html.DisplayNameFor(model => model.ProductsPlans.FirstOrDefault().Count)
                </a>
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ProductsPlans)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DayPlan.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.ProductPlan">Изменить</a> |
                <a class="btn btn-outline-dark" asp-action="Delete" asp-route-id="@item.ProductPlan">Удалить</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}